-- ====================================================================
-- RAJMUDRA GROUP PWA - SUPABASE-ONLY SCHEMA AND SAFE MIGRATION
-- ====================================================================
-- Run this in the Supabase SQL Editor before deploying the Supabase-only
-- frontend. It is additive: it does not delete existing ledger rows.
--
-- Migration notes
-- 1. Take a Supabase backup first.
-- 2. Existing BIGINT primary keys are retained. `BY DEFAULT` identity
--    columns accept old client-supplied IDs during the transition, while
--    the new client can omit `id` and receive a database-generated value.
-- 3. The identity sequences are advanced beyond existing IDs, so they do
--    not collide with legacy Date.now()-style values.
-- 4. After the frontend rollout, treat Supabase as the only source of
--    truth; do not import stale browser-storage backups automatically.
-- ====================================================================

-- 1. Members
CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Vargani (donations)
CREATE TABLE IF NOT EXISTS public.vargani (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix TEXT NOT NULL DEFAULT 'श्री',
    member_id BIGINT,
    member_name TEXT NOT NULL,
    phone TEXT NOT NULL DEFAULT '',
    year TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    payment_mode TEXT NOT NULL DEFAULT 'Cash',
    status TEXT NOT NULL DEFAULT 'paid',
    date DATE NOT NULL,
    receipt_no TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Jama (income)
CREATE TABLE IF NOT EXISTS public.jama (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    year TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    payment_mode TEXT NOT NULL DEFAULT 'Cash',
    date DATE NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Kharch (expenses)
CREATE TABLE IF NOT EXISTS public.kharch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    year TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    payment_mode TEXT NOT NULL DEFAULT 'Cash',
    date DATE NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Aarti schedule
CREATE TABLE IF NOT EXISTS public.aarti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year TEXT NOT NULL,
    day_title TEXT NOT NULL,
    date DATE NOT NULL,
    morning_time TEXT NOT NULL DEFAULT '09.00 AM',
    morning_host TEXT NOT NULL DEFAULT '',
    evening_time TEXT NOT NULL DEFAULT '08.00 PM',
    evening_host TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Bank FD and treasury
CREATE TABLE IF NOT EXISTS public.bank_fd (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'deposit',
    year TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    interest_rate NUMERIC NOT NULL DEFAULT 0,
    expected_returns NUMERIC NOT NULL DEFAULT 0,
    bank_name TEXT NOT NULL DEFAULT 'Mandal Bank FD Account',
    date DATE NOT NULL,
    expiry_date DATE,
    renewed_from_id BIGINT REFERENCES public.bank_fd(id),
    holder_name TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Shared, non-secret application settings. Store one JSON object under
--    the `global` key (for example, {"active_year":"2026-27"}). Do not
--    store PINs, credentials, or other secrets here; use Supabase Auth.
CREATE TABLE IF NOT EXISTS public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT NOT NULL UNIQUE,
    setting_value JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.app_settings (setting_key, setting_value)
VALUES ('global', '{"active_year":"2026-27"}'::JSONB)
ON CONFLICT (setting_key) DO NOTHING;

-- ====================================================================
-- EXISTING-DEPLOYMENT UPGRADES
-- ====================================================================

-- Add the timestamp used for deterministic refreshes to installations made
-- with the previous schema. `IF NOT EXISTS` makes these statements rerunnable.
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.vargani ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.jama ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.kharch ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.kharch ADD COLUMN IF NOT EXISTS payment_mode TEXT NOT NULL DEFAULT 'Cash';
ALTER TABLE public.aarti ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.bank_fd ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.bank_fd ADD COLUMN IF NOT EXISTS holder_name TEXT NOT NULL DEFAULT '';
ALTER TABLE public.bank_fd ADD COLUMN IF NOT EXISTS renewed_from_id BIGINT REFERENCES public.bank_fd(id);

-- Upgrade the original `BIGINT PRIMARY KEY` columns to generated identities
-- without changing their type or existing values.
DO $$
DECLARE
    target_table TEXT;
BEGIN
    FOREACH target_table IN ARRAY ARRAY['members', 'vargani', 'jama', 'kharch', 'aarti', 'bank_fd']
    LOOP
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = target_table
              AND column_name = 'id'
              AND is_identity = 'YES'
        ) THEN
            EXECUTE format(
                'ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
                target_table
            );
        END IF;
    END LOOP;
END $$;

-- Align every newly-created identity sequence with existing rows. This avoids
-- a generated ID colliding with an older explicit ID.
DO $$
DECLARE
    target_table TEXT;
    sequence_name TEXT;
BEGIN
    FOREACH target_table IN ARRAY ARRAY['members', 'vargani', 'jama', 'kharch', 'aarti', 'bank_fd']
    LOOP
        sequence_name := pg_get_serial_sequence(format('public.%I', target_table), 'id');
        IF sequence_name IS NOT NULL THEN
            EXECUTE format(
                'SELECT setval(%L, COALESCE(MAX(id), 1), COUNT(*) > 0) FROM public.%I',
                sequence_name,
                target_table
            );
        END IF;
    END LOOP;
END $$;

-- Keep updated_at current for direct mutations, including those made outside
-- the frontend.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_members_updated_at ON public.members;
CREATE TRIGGER set_members_updated_at
BEFORE UPDATE ON public.members
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_vargani_updated_at ON public.vargani;
CREATE TRIGGER set_vargani_updated_at
BEFORE UPDATE ON public.vargani
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_jama_updated_at ON public.jama;
CREATE TRIGGER set_jama_updated_at
BEFORE UPDATE ON public.jama
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_kharch_updated_at ON public.kharch;
CREATE TRIGGER set_kharch_updated_at
BEFORE UPDATE ON public.kharch
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_aarti_updated_at ON public.aarti;
CREATE TRIGGER set_aarti_updated_at
BEFORE UPDATE ON public.aarti
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_bank_fd_updated_at ON public.bank_fd;
CREATE TRIGGER set_bank_fd_updated_at
BEFORE UPDATE ON public.bank_fd
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_app_settings_updated_at ON public.app_settings;
CREATE TRIGGER set_app_settings_updated_at
BEFORE UPDATE ON public.app_settings
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ====================================================================
-- PERFORMANCE INDEXES
-- ====================================================================
-- The client fetches a fiscal year ordered by entry date. These composite
-- indexes avoid full-table scans as ledger history grows.
CREATE INDEX IF NOT EXISTS idx_vargani_year_date ON public.vargani(year, date DESC);
CREATE INDEX IF NOT EXISTS idx_vargani_member_id ON public.vargani(member_id);
CREATE INDEX IF NOT EXISTS idx_jama_year_date ON public.jama(year, date DESC);
CREATE INDEX IF NOT EXISTS idx_kharch_year_date ON public.kharch(year, date DESC);
CREATE INDEX IF NOT EXISTS idx_aarti_year_date ON public.aarti(year, date ASC);
CREATE INDEX IF NOT EXISTS idx_bank_fd_year_date ON public.bank_fd(year, date DESC);

-- ====================================================================
-- REALTIME PUBLICATION
-- ====================================================================
-- This is safe to rerun and enables table-change subscriptions when the
-- Supabase project has its normal `supabase_realtime` publication.
DO $$
DECLARE
    target_table TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        FOREACH target_table IN ARRAY ARRAY['members', 'vargani', 'jama', 'kharch', 'aarti', 'bank_fd', 'app_settings']
        LOOP
            IF NOT EXISTS (
                SELECT 1
                FROM pg_publication_tables
                WHERE pubname = 'supabase_realtime'
                  AND schemaname = 'public'
                  AND tablename = target_table
            ) THEN
                EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', target_table);
            END IF;
        END LOOP;
    END IF;
END $$;

-- ====================================================================
-- ROW LEVEL SECURITY
-- ====================================================================
-- These anonymous policies preserve compatibility with the present app while
-- it has no Supabase Auth integration. They are NOT appropriate for a public
-- production deployment. Before exposing the URL publicly, replace them with
-- authenticated, organization-scoped policies and keep secrets out of tables.

ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vargani ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jama ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kharch ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aarti ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_fd ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon full access members" ON public.members;
CREATE POLICY "Allow anon full access members" ON public.members FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access vargani" ON public.vargani;
CREATE POLICY "Allow anon full access vargani" ON public.vargani FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access jama" ON public.jama;
CREATE POLICY "Allow anon full access jama" ON public.jama FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access kharch" ON public.kharch;
CREATE POLICY "Allow anon full access kharch" ON public.kharch FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access aarti" ON public.aarti;
CREATE POLICY "Allow anon full access aarti" ON public.aarti FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access bank_fd" ON public.bank_fd;
CREATE POLICY "Allow anon full access bank_fd" ON public.bank_fd FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access app settings" ON public.app_settings;
CREATE POLICY "Allow anon full access app settings" ON public.app_settings FOR ALL TO anon USING (true) WITH CHECK (true);
