-- ====================================================================
-- RAJMUDRA GROUP PWA - SUPABASE-ONLY SCHEMA AND SAFE MIGRATION
-- ====================================================================
-- Run this in the Supabase SQL Editor before deploying the Supabase-only
-- frontend. It is additive: it does not delete existing ledger rows.
--
-- Migration notes
-- 1. Take a Supabase backup first.
-- 2. Existing BIGINT primary keys are retained. `BY DEFAULT` identity
--    columns accept old client-supplied IDs during the transition, while
--    the new client can omit `id` and receive a database-generated value.
-- 3. The identity sequences are advanced beyond existing IDs, so they do
--    not collide with legacy Date.now()-style values.
-- 4. After the frontend rollout, treat Supabase as the only source of
--    truth; do not import stale browser-storage backups automatically.
-- ====================================================================

-- 1. Members
CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Vargani (donations)
CREATE TABLE IF NOT EXISTS public.vargani (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix TEXT NOT NULL DEFAULT 'श्री',
    member_id BIGINT,
    member_name TEXT NOT NULL,
    phone TEXT NOT NULL DEFAULT '',
    year TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    payment_mode TEXT NOT NULL DEFAULT 'Cash',
    status TEXT NOT NULL DEFAULT 'paid',
    date DATE NOT NULL,
    receipt_no TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Jama (income)
CREATE TABLE IF NOT EXISTS public.jama (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    year TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    payment_mode TEXT NOT NULL DEFAULT 'Cash',
    date DATE NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Kharch (expenses)
CREATE TABLE IF NOT EXISTS public.kharch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    year TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    payment_mode TEXT NOT NULL DEFAULT 'Cash',
    date DATE NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Aarti schedule
CREATE TABLE IF NOT EXISTS public.aarti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year TEXT NOT NULL,
    day_title TEXT NOT NULL,
    date DATE NOT NULL,
    morning_time TEXT NOT NULL DEFAULT '09.00 AM',
    morning_host TEXT NOT NULL DEFAULT '',
    evening_time TEXT NOT NULL DEFAULT '08.00 PM',
    evening_host TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Bank FD and treasury
CREATE TABLE IF NOT EXISTS public.bank_fd (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'cash_to_bank' CHECK (type IN ('cash_to_bank', 'upi_to_bank', 'bank_to_cash', 'bank_to_upi', 'renew')),
    year TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    interest_rate NUMERIC NOT NULL DEFAULT 0,
    expected_returns NUMERIC NOT NULL DEFAULT 0,
    bank_name TEXT NOT NULL DEFAULT 'Mandal Bank FD Account',
    date DATE NOT NULL,
    expiry_date DATE,
    renewed_from_id BIGINT REFERENCES public.bank_fd(id),
    withdrawn_from_id BIGINT REFERENCES public.bank_fd(id),
    renewal_extra_amount NUMERIC NOT NULL DEFAULT 0,
    renewal_extra_source TEXT NOT NULL DEFAULT '',
    holder_name TEXT NOT NULL DEFAULT '',
    note TEXT NOT NULL DEFAULT '',
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Shared, non-secret application settings. Store one JSON object under
--    the `global` key (for example, {"active_year":"2026-27"}). Do not
--    store PINs, credentials, or other secrets here; use Supabase Auth.
CREATE TABLE IF NOT EXISTS public.app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT NOT NULL UNIQUE,
    setting_value JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.app_settings (setting_key, setting_value)
VALUES ('global', '{"active_year":"2026-27"}'::JSONB)
ON CONFLICT (setting_key) DO NOTHING;

-- ====================================================================
-- EXISTING-DEPLOYMENT UPGRADES
-- ====================================================================

-- Add the timestamp used for deterministic refreshes to installations made
-- with the previous schema. `IF NOT EXISTS` makes these statements rerunnable.
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.vargani ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.jama ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.kharch ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.kharch ADD COLUMN IF NOT EXISTS payment_mode TEXT NOT NULL DEFAULT 'Cash';
ALTER TABLE public.aarti ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.bank_fd ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE public.bank_fd ADD COLUMN IF NOT EXISTS holder_name TEXT NOT NULL DEFAULT '';
ALTER TABLE public.bank_fd ADD COLUMN IF NOT EXISTS renewed_from_id BIGINT REFERENCES public.bank_fd(id);
ALTER TABLE public.bank_fd ADD COLUMN IF NOT EXISTS withdrawn_from_id BIGINT REFERENCES public.bank_fd(id);
ALTER TABLE public.bank_fd ADD COLUMN IF NOT EXISTS renewal_extra_amount NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE public.bank_fd ADD COLUMN IF NOT EXISTS renewal_extra_source TEXT NOT NULL DEFAULT '';

-- Upgrade the original `BIGINT PRIMARY KEY` columns to generated identities
-- without changing their type or existing values.
DO $$
DECLARE
    target_table TEXT;
BEGIN
    FOREACH target_table IN ARRAY ARRAY['members', 'vargani', 'jama', 'kharch', 'aarti', 'bank_fd']
    LOOP
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = target_table
              AND column_name = 'id'
              AND is_identity = 'YES'
        ) THEN
            EXECUTE format(
                'ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
                target_table
            );
        END IF;
    END LOOP;
END $$;

-- Align every newly-created identity sequence with existing rows. This avoids
-- a generated ID colliding with an older explicit ID.
DO $$
DECLARE
    target_table TEXT;
    sequence_name TEXT;
BEGIN
    FOREACH target_table IN ARRAY ARRAY['members', 'vargani', 'jama', 'kharch', 'aarti', 'bank_fd']
    LOOP
        sequence_name := pg_get_serial_sequence(format('public.%I', target_table), 'id');
        IF sequence_name IS NOT NULL THEN
            EXECUTE format(
                'SELECT setval(%L, COALESCE(MAX(id), 1), COUNT(*) > 0) FROM public.%I',
                sequence_name,
                target_table
            );
        END IF;
    END LOOP;
END $$;

-- Keep updated_at current for direct mutations, including those made outside
-- the frontend.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_members_updated_at ON public.members;
CREATE TRIGGER set_members_updated_at
BEFORE UPDATE ON public.members
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_vargani_updated_at ON public.vargani;
CREATE TRIGGER set_vargani_updated_at
BEFORE UPDATE ON public.vargani
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_jama_updated_at ON public.jama;
CREATE TRIGGER set_jama_updated_at
BEFORE UPDATE ON public.jama
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_kharch_updated_at ON public.kharch;
CREATE TRIGGER set_kharch_updated_at
BEFORE UPDATE ON public.kharch
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_aarti_updated_at ON public.aarti;
CREATE TRIGGER set_aarti_updated_at
BEFORE UPDATE ON public.aarti
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_bank_fd_updated_at ON public.bank_fd;
CREATE TRIGGER set_bank_fd_updated_at
BEFORE UPDATE ON public.bank_fd
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS set_app_settings_updated_at ON public.app_settings;
CREATE TRIGGER set_app_settings_updated_at
BEFORE UPDATE ON public.app_settings
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ====================================================================
-- PERFORMANCE INDEXES
-- ====================================================================
-- The client fetches a fiscal year ordered by entry date. These composite
-- indexes avoid full-table scans as ledger history grows.
CREATE INDEX IF NOT EXISTS idx_vargani_year_date ON public.vargani(year, date DESC);
CREATE INDEX IF NOT EXISTS idx_vargani_member_id ON public.vargani(member_id);
-- Receipt numbers may be blank, but a non-blank receipt can be used only once
-- in a festival year. The normalized expression also treats "001" and "001 "
-- (or differently cased text) as the same receipt.
CREATE UNIQUE INDEX IF NOT EXISTS idx_vargani_year_receipt_no_unique
ON public.vargani(year, lower(btrim(receipt_no)))
WHERE btrim(receipt_no) <> '';
CREATE INDEX IF NOT EXISTS idx_jama_year_date ON public.jama(year, date DESC);
CREATE INDEX IF NOT EXISTS idx_kharch_year_date ON public.kharch(year, date DESC);
CREATE INDEX IF NOT EXISTS idx_aarti_year_date ON public.aarti(year, date ASC);
CREATE INDEX IF NOT EXISTS idx_bank_fd_year_date ON public.bank_fd(year, date DESC);

-- ====================================================================
-- REALTIME PUBLICATION
-- ====================================================================
-- This is safe to rerun and enables table-change subscriptions when the
-- Supabase project has its normal `supabase_realtime` publication.
DO $$
DECLARE
    target_table TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        FOREACH target_table IN ARRAY ARRAY['members', 'vargani', 'jama', 'kharch', 'aarti', 'bank_fd', 'app_settings']
        LOOP
            IF NOT EXISTS (
                SELECT 1
                FROM pg_publication_tables
                WHERE pubname = 'supabase_realtime'
                  AND schemaname = 'public'
                  AND tablename = target_table
            ) THEN
                EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', target_table);
            END IF;
        END LOOP;
    END IF;
END $$;

-- ====================================================================
-- ROW LEVEL SECURITY
-- ====================================================================
-- These anonymous policies preserve compatibility with the present app while
-- it has no Supabase Auth integration. They are NOT appropriate for a public
-- production deployment. Before exposing the URL publicly, replace them with
-- authenticated, organization-scoped policies and keep secrets out of tables.

ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vargani ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jama ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kharch ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aarti ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_fd ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon full access members" ON public.members;
CREATE POLICY "Allow anon full access members" ON public.members FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access vargani" ON public.vargani;
CREATE POLICY "Allow anon full access vargani" ON public.vargani FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access jama" ON public.jama;
CREATE POLICY "Allow anon full access jama" ON public.jama FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access kharch" ON public.kharch;
CREATE POLICY "Allow anon full access kharch" ON public.kharch FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access aarti" ON public.aarti;
CREATE POLICY "Allow anon full access aarti" ON public.aarti FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access bank_fd" ON public.bank_fd;
CREATE POLICY "Allow anon full access bank_fd" ON public.bank_fd FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon full access app settings" ON public.app_settings;
CREATE POLICY "Allow anon full access app settings" ON public.app_settings FOR ALL TO anon USING (true) WITH CHECK (true);

-- ====================================================================
-- FINAL FINANCIAL RULES AND AUTHENTICATED ACCESS
-- This section replaces the former separate migration files. It is safe to
-- run on an existing installation as well as a new project.
-- ====================================================================

ALTER TABLE public.vargani DROP CONSTRAINT IF EXISTS vargani_amount_positive;
ALTER TABLE public.vargani ADD CONSTRAINT vargani_amount_positive CHECK (amount > 0) NOT VALID;
ALTER TABLE public.jama DROP CONSTRAINT IF EXISTS jama_amount_positive;
ALTER TABLE public.jama ADD CONSTRAINT jama_amount_positive CHECK (amount > 0) NOT VALID;
ALTER TABLE public.kharch DROP CONSTRAINT IF EXISTS kharch_amount_positive;
ALTER TABLE public.kharch ADD CONSTRAINT kharch_amount_positive CHECK (amount > 0) NOT VALID;
ALTER TABLE public.bank_fd DROP CONSTRAINT IF EXISTS bank_fd_amount_positive;
ALTER TABLE public.bank_fd ADD CONSTRAINT bank_fd_amount_positive CHECK (amount > 0) NOT VALID;
ALTER TABLE public.vargani DROP CONSTRAINT IF EXISTS vargani_payment_mode_valid;
ALTER TABLE public.vargani ADD CONSTRAINT vargani_payment_mode_valid CHECK (BTRIM(payment_mode) IN ('Cash', 'UPI', 'Online')) NOT VALID;
ALTER TABLE public.jama DROP CONSTRAINT IF EXISTS jama_payment_mode_valid;
ALTER TABLE public.jama ADD CONSTRAINT jama_payment_mode_valid CHECK (BTRIM(payment_mode) IN ('Cash', 'UPI', 'Online')) NOT VALID;
ALTER TABLE public.kharch DROP CONSTRAINT IF EXISTS kharch_payment_mode_valid;
ALTER TABLE public.kharch ADD CONSTRAINT kharch_payment_mode_valid CHECK (BTRIM(payment_mode) IN ('Cash', 'UPI', 'Online')) NOT VALID;
ALTER TABLE public.vargani DROP CONSTRAINT IF EXISTS vargani_status_valid;
ALTER TABLE public.vargani ADD CONSTRAINT vargani_status_valid CHECK (status IN ('paid', 'pending')) NOT VALID;
ALTER TABLE public.bank_fd DROP CONSTRAINT IF EXISTS bank_fd_renewal_extra_valid;
ALTER TABLE public.bank_fd ADD CONSTRAINT bank_fd_renewal_extra_valid
  CHECK (renewal_extra_amount >= 0 AND (renewal_extra_amount = 0 OR renewal_extra_source IN ('Cash', 'UPI'))) NOT VALID;
ALTER TABLE public.bank_fd ALTER COLUMN type SET DEFAULT 'cash_to_bank';
ALTER TABLE public.bank_fd DROP CONSTRAINT IF EXISTS bank_fd_simple_fd_types;
ALTER TABLE public.bank_fd ADD CONSTRAINT bank_fd_simple_fd_types
  CHECK (type IN ('cash_to_bank', 'upi_to_bank', 'bank_to_cash', 'bank_to_upi', 'renew')) NOT VALID;
CREATE INDEX IF NOT EXISTS idx_bank_fd_renewed_from_id ON public.bank_fd(renewed_from_id) WHERE renewed_from_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bank_fd_withdrawn_from_id ON public.bank_fd(withdrawn_from_id) WHERE withdrawn_from_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.rajmudra_bank_balance(p_exclude_bank_fd_id BIGINT DEFAULT NULL)
RETURNS NUMERIC LANGUAGE sql STABLE SET search_path = public AS $$
  WITH entries AS (
    SELECT id, type, amount, renewed_from_id, withdrawn_from_id FROM public.bank_fd
    WHERE p_exclude_bank_fd_id IS NULL OR id <> p_exclude_bank_fd_id
  ), renewed_sources AS (
    SELECT renewed_from_id FROM entries WHERE type = 'renew' AND renewed_from_id IS NOT NULL
  )
  SELECT COALESCE(SUM(CASE
    WHEN id IN (SELECT renewed_from_id FROM renewed_sources) THEN 0
    WHEN type IN ('bank_to_cash', 'bank_to_upi') AND withdrawn_from_id IN (SELECT renewed_from_id FROM renewed_sources) THEN 0
    WHEN type IN ('deposit', 'renew', 'cash_to_bank', 'upi_to_bank', 'interest', 'bank_income') THEN amount
    WHEN type IN ('withdrawal', 'bank_to_cash', 'bank_to_upi', 'fd_expense', 'charge', 'bank_expense') THEN -amount
    ELSE 0 END), 0) FROM entries;
$$;

CREATE OR REPLACE FUNCTION public.rajmudra_treasury_balances(
  p_year TEXT, p_exclude_kharch_id BIGINT DEFAULT NULL, p_exclude_bank_fd_id BIGINT DEFAULT NULL
)
RETURNS TABLE (cash_balance NUMERIC, online_balance NUMERIC)
LANGUAGE sql STABLE SET search_path = public AS $$
  WITH income AS (
    SELECT payment_mode, amount FROM public.vargani WHERE year = p_year AND COALESCE(status, 'paid') = 'paid'
    UNION ALL SELECT payment_mode, amount FROM public.jama WHERE year = p_year
  ), expenses AS (
    SELECT payment_mode, amount FROM public.kharch WHERE year = p_year AND (p_exclude_kharch_id IS NULL OR id <> p_exclude_kharch_id)
  ), movements AS (
    SELECT type, amount, renewal_extra_amount, renewal_extra_source FROM public.bank_fd
    WHERE year = p_year AND (p_exclude_bank_fd_id IS NULL OR id <> p_exclude_bank_fd_id)
  )
  SELECT
    COALESCE((SELECT SUM(CASE WHEN LOWER(BTRIM(COALESCE(payment_mode, 'Cash'))) = 'cash' THEN amount ELSE 0 END) FROM income), 0)
      - COALESCE((SELECT SUM(CASE WHEN LOWER(BTRIM(COALESCE(payment_mode, 'Cash'))) = 'cash' THEN amount ELSE 0 END) FROM expenses), 0)
      + COALESCE((SELECT SUM(CASE WHEN type IN ('upi_to_cash', 'bank_to_cash') THEN amount WHEN type IN ('cash_to_upi', 'cash_to_bank') THEN -amount WHEN type = 'renew' AND renewal_extra_source = 'Cash' THEN -renewal_extra_amount ELSE 0 END) FROM movements), 0),
    COALESCE((SELECT SUM(CASE WHEN LOWER(BTRIM(COALESCE(payment_mode, 'Cash'))) <> 'cash' THEN amount ELSE 0 END) FROM income), 0)
      - COALESCE((SELECT SUM(CASE WHEN LOWER(BTRIM(COALESCE(payment_mode, 'Cash'))) <> 'cash' THEN amount ELSE 0 END) FROM expenses), 0)
      + COALESCE((SELECT SUM(CASE WHEN type IN ('cash_to_upi', 'bank_to_upi') THEN amount WHEN type IN ('upi_to_cash', 'upi_to_bank') THEN -amount WHEN type = 'renew' AND renewal_extra_amount > 0 AND renewal_extra_source = 'UPI' THEN -renewal_extra_amount ELSE 0 END) FROM movements), 0);
$$;

CREATE OR REPLACE FUNCTION public.rajmudra_validate_expense_balance()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
DECLARE balances RECORD; available NUMERIC; old_id BIGINT := NULL;
BEGIN
  IF TG_OP = 'UPDATE' THEN old_id := OLD.id; END IF;
  PERFORM pg_advisory_xact_lock(hashtext('rajmudra:treasury:' || NEW.year));
  SELECT * INTO balances FROM public.rajmudra_treasury_balances(NEW.year, old_id, NULL);
  available := CASE WHEN LOWER(BTRIM(COALESCE(NEW.payment_mode, 'Cash'))) = 'cash' THEN balances.cash_balance ELSE balances.online_balance END;
  IF NEW.amount > available THEN RAISE EXCEPTION 'Insufficient % balance. Available: Rs. %', NEW.payment_mode, available USING ERRCODE = 'P0001'; END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.rajmudra_validate_bank_entry_balance()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
DECLARE balances RECORD; available NUMERIC; bank_before NUMERIC; bank_after NUMERIC; source_available NUMERIC; old_id BIGINT := NULL; bank_delta NUMERIC := 0;
BEGIN
  IF TG_OP = 'UPDATE' THEN old_id := OLD.id; END IF;
  PERFORM pg_advisory_xact_lock(hashtext('rajmudra:bank'));
  PERFORM pg_advisory_xact_lock(hashtext('rajmudra:treasury:' || NEW.year));
  IF TG_OP = 'UPDATE' AND (
    EXISTS (SELECT 1 FROM public.bank_fd WHERE type = 'renew' AND renewed_from_id = OLD.id)
    OR EXISTS (SELECT 1 FROM public.bank_fd withdrawal WHERE withdrawal.type IN ('bank_to_cash', 'bank_to_upi') AND withdrawal.withdrawn_from_id = OLD.id)
    OR (OLD.type IN ('bank_to_cash', 'bank_to_upi') AND EXISTS (SELECT 1 FROM public.bank_fd renewal WHERE renewal.type = 'renew' AND renewal.renewed_from_id = OLD.withdrawn_from_id))
  ) THEN RAISE EXCEPTION 'This entry is part of a completed FD renewal and cannot be changed.' USING ERRCODE = 'P0001'; END IF;
  IF NEW.type IN ('cash_to_bank', 'upi_to_bank') THEN
    SELECT * INTO balances FROM public.rajmudra_treasury_balances(NEW.year, NULL, old_id);
    available := CASE WHEN NEW.type = 'cash_to_bank' THEN balances.cash_balance ELSE balances.online_balance END;
    IF NEW.amount > available THEN RAISE EXCEPTION 'Insufficient source balance. Available: Rs. %', available USING ERRCODE = 'P0001'; END IF;
  END IF;
  IF NEW.type IN ('bank_to_cash', 'bank_to_upi') THEN
    IF NEW.withdrawn_from_id IS NULL THEN RAISE EXCEPTION 'Select the FD being withdrawn.' USING ERRCODE = 'P0001'; END IF;
    SELECT source.amount - COALESCE((SELECT SUM(withdrawal.amount) FROM public.bank_fd withdrawal WHERE withdrawal.type IN ('bank_to_cash', 'bank_to_upi') AND withdrawal.withdrawn_from_id = source.id AND (old_id IS NULL OR withdrawal.id <> old_id)), 0)
      INTO source_available FROM public.bank_fd source WHERE source.id = NEW.withdrawn_from_id AND source.type IN ('deposit', 'renew', 'cash_to_bank', 'upi_to_bank')
        AND NOT EXISTS (SELECT 1 FROM public.bank_fd later_renewal WHERE later_renewal.type = 'renew' AND later_renewal.renewed_from_id = source.id);
    IF source_available IS NULL OR NEW.amount > source_available THEN RAISE EXCEPTION 'Insufficient balance in the selected FD. Available: Rs. %', COALESCE(source_available, 0) USING ERRCODE = 'P0001'; END IF;
  END IF;
  bank_before := public.rajmudra_bank_balance(old_id);
  IF NEW.type = 'renew' THEN
    IF NEW.renewed_from_id IS NULL THEN RAISE EXCEPTION 'Select the old FD being renewed.' USING ERRCODE = 'P0001'; END IF;
    SELECT source.amount - COALESCE((SELECT SUM(withdrawal.amount) FROM public.bank_fd withdrawal WHERE withdrawal.type IN ('bank_to_cash', 'bank_to_upi') AND withdrawal.withdrawn_from_id = source.id), 0)
      INTO source_available FROM public.bank_fd source WHERE source.id = NEW.renewed_from_id AND source.type IN ('deposit', 'renew', 'cash_to_bank', 'upi_to_bank')
        AND NOT EXISTS (SELECT 1 FROM public.bank_fd later_renewal WHERE later_renewal.type = 'renew' AND later_renewal.renewed_from_id = source.id AND (old_id IS NULL OR later_renewal.id <> old_id));
    IF source_available IS NULL THEN RAISE EXCEPTION 'The selected FD is unavailable for renewal.' USING ERRCODE = 'P0001'; END IF;
    IF NEW.amount < source_available + NEW.renewal_extra_amount THEN RAISE EXCEPTION 'The renewed total must include the selected FD balance and any top-up.' USING ERRCODE = 'P0001'; END IF;
    IF NEW.renewal_extra_amount > 0 THEN
      SELECT * INTO balances FROM public.rajmudra_treasury_balances(NEW.year, NULL, old_id);
      available := CASE WHEN NEW.renewal_extra_source = 'Cash' THEN balances.cash_balance ELSE balances.online_balance END;
      IF NEW.renewal_extra_amount > available THEN RAISE EXCEPTION 'Insufficient % balance for the renewal top-up. Available: Rs. %', NEW.renewal_extra_source, available USING ERRCODE = 'P0001'; END IF;
    END IF;
    bank_after := bank_before - source_available + NEW.amount;
  ELSE
    bank_delta := CASE WHEN NEW.type IN ('deposit', 'cash_to_bank', 'upi_to_bank', 'interest', 'bank_income') THEN NEW.amount WHEN NEW.type IN ('withdrawal', 'bank_to_cash', 'bank_to_upi', 'fd_expense', 'charge', 'bank_expense') THEN -NEW.amount ELSE 0 END;
    bank_after := bank_before + bank_delta;
  END IF;
  IF bank_after < 0 THEN RAISE EXCEPTION 'Insufficient Bank / FD balance. Available: Rs. %', bank_before USING ERRCODE = 'P0001'; END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS validate_kharch_balance ON public.kharch;
CREATE TRIGGER validate_kharch_balance BEFORE INSERT OR UPDATE OF amount, payment_mode, year ON public.kharch FOR EACH ROW EXECUTE FUNCTION public.rajmudra_validate_expense_balance();
DROP TRIGGER IF EXISTS validate_bank_fd_balance ON public.bank_fd;
CREATE TRIGGER validate_bank_fd_balance BEFORE INSERT OR UPDATE OF amount, type, year, renewed_from_id, withdrawn_from_id, renewal_extra_amount, renewal_extra_source ON public.bank_fd FOR EACH ROW EXECUTE FUNCTION public.rajmudra_validate_bank_entry_balance();

CREATE OR REPLACE FUNCTION public.rajmudra_prevent_linked_fd_delete()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.bank_fd WHERE type = 'renew' AND renewed_from_id = OLD.id)
    OR (OLD.type IN ('bank_to_cash', 'bank_to_upi') AND EXISTS (SELECT 1 FROM public.bank_fd renewal WHERE renewal.type = 'renew' AND renewal.renewed_from_id = OLD.withdrawn_from_id))
  THEN RAISE EXCEPTION 'This entry is part of a completed FD renewal and cannot be deleted independently.' USING ERRCODE = 'P0001'; END IF;
  RETURN OLD;
END;
$$;
DROP TRIGGER IF EXISTS prevent_renewed_fd_source_delete ON public.bank_fd;
DROP TRIGGER IF EXISTS prevent_linked_fd_delete ON public.bank_fd;
CREATE TRIGGER prevent_linked_fd_delete BEFORE DELETE ON public.bank_fd FOR EACH ROW EXECUTE FUNCTION public.rajmudra_prevent_linked_fd_delete();

-- Secure Supabase Auth roles and read-only viewers.
CREATE TABLE IF NOT EXISTS public.user_roles (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('admin', 'viewer')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.is_rajmudra_admin()
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = (SELECT auth.uid()) AND role = 'admin');
$$;
REVOKE ALL ON FUNCTION public.is_rajmudra_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_rajmudra_admin() TO authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
DO $$
DECLARE target_table TEXT;
BEGIN
  FOREACH target_table IN ARRAY ARRAY['members', 'vargani', 'jama', 'kharch', 'aarti', 'bank_fd', 'app_settings'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', target_table);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'Allow anon full access ' || target_table, target_table);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'Rajmudra authenticated read ' || target_table, target_table);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'Rajmudra admins manage ' || target_table, target_table);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (true)', 'Rajmudra authenticated read ' || target_table, target_table);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO authenticated USING ((SELECT public.is_rajmudra_admin())) WITH CHECK ((SELECT public.is_rajmudra_admin()))', 'Rajmudra admins manage ' || target_table, target_table);
  END LOOP;
END $$;
DROP POLICY IF EXISTS "Users can read their own Rajmudra role" ON public.user_roles;
CREATE POLICY "Users can read their own Rajmudra role" ON public.user_roles FOR SELECT TO authenticated USING ((SELECT auth.uid()) = user_id);

-- Permanently remove orphan/test members and remove a member only when its
-- final donation is deleted.
DELETE FROM public.members AS member WHERE NOT EXISTS (SELECT 1 FROM public.vargani AS donation WHERE donation.member_id = member.id);
CREATE OR REPLACE FUNCTION public.delete_vargani_and_orphan_member(p_vargani_id BIGINT)
RETURNS TABLE (deleted_vargani_id BIGINT, deleted_member_id BIGINT)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE removed_vargani_id BIGINT; donation_member_id BIGINT; removed_member_id BIGINT := NULL;
BEGIN
  IF NOT COALESCE(public.is_rajmudra_admin(), FALSE) THEN RAISE EXCEPTION 'Only an administrator can delete a donation.' USING ERRCODE = '42501'; END IF;
  DELETE FROM public.vargani WHERE id = p_vargani_id RETURNING id, member_id INTO removed_vargani_id, donation_member_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Donation % was not found.', p_vargani_id USING ERRCODE = 'P0002'; END IF;
  IF donation_member_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.vargani WHERE member_id = donation_member_id) THEN
    DELETE FROM public.members WHERE id = donation_member_id RETURNING id INTO removed_member_id;
  END IF;
  RETURN QUERY SELECT removed_vargani_id, removed_member_id;
END;
$$;
REVOKE ALL ON FUNCTION public.delete_vargani_and_orphan_member(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_vargani_and_orphan_member(BIGINT) TO authenticated;
NOTIFY pgrst, 'reload schema';
